server:
  port: 9999

spring:
  application:
    name: API-GATEWAY
  cloud:
    nacos:
      server-addr: 114.116.65.212:8848
    gateway:
      globalcors: # 跨域配置处理

        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 360000
      routes:
        # admins router
        - id: admins_router
          uri: lb://API-ADMINS
          predicates:
            - Path=/admin/demos,/admin/tokens,/admin/admin-user,/admin/tokens/**
          filters:
            - StripPrefix=1   #去掉请求前缀filter    int数字  1 去掉一级   2 去掉两级


        # category router
        - id: category_router
          uri: lb://API-CATEGROYS
          predicates:
            - Path=/admin/categories/**
          filters:
            - StripPrefix=1   #去掉请求前缀filter    int数字  1 去掉一级   2 去掉两级
            - Token=true,xiaochen      #进行token认证filter

        # users router
        - id: users_router
          uri: lb://API-USERS
          predicates:
            - Path=/admin/users/**
          filters:
            - StripPrefix=1   #去掉请求前缀filter    int数字  1 去掉一级   2 去掉两级
            - Token=true

        # videos router
        - id: videos_router
          uri: lb://API-VIDEOS
          predicates:
            - Path=/admin/videos/**
          filters:
            - StripPrefix=1   #去掉请求前缀filter    int数字  1 去掉一级   2 去掉两级
            - Token=true

  redis:
    port: 6379
    host: 114.116.65.212


