server:
  port: 9992

spring:
  application:
    name: API-USERS
  cloud:
    nacos:
      discovery:
        server-addr: 114.116.65.212:8848
  redis:
    host: 114.116.65.212
    port: 6379

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gz-cynosdbmysql-grp-c2m0jzh1.sql.tencentcdb.com:25224/videos?characterEncoding=UTF-8&useSSL=false
    username: root
    password: Qwer1793!

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:com/hjh/mapper/*.xml
  type-aliases-package: com.hjh.entity

logging:
  level:
    com:
      hjh:
        dao: debug

#设置openfeign调用超时
feign:
  client:
    config:
      default:
        connectTimeout: 100000
        readTimeout: 100000

oss:
  accesskeyId: 
  secret: 