version: "3.9"

networks:
  videos_network:

volumes:
  data:
  redisdata:
  mqdata:

services:
  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: nacos
    ports:
      - "8848:8848"
    environment:
      - "JVM_XMS=256m"
      - "JVM_XMX=256m"
      - "MODE=standalone"
    networks:
      - videos_network

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - videos_network
    volumes:
      - /home/hjh/videos/mysql/data:/var/lib/mysql
      - /home/hjh/videos/mysql/conf/my.cnf:/var/log/mysql
      - ./videos.sql:/docker-entrypoint-initdb.d/videos.sql
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=videos"


  redis:
    ports:
      - 6379:6379
    container_name: redis
    image: redis:5.0.10
    privileged: true
    volumes:
      - /home/hjh/videos/redis/data:/data
      - /home/hjh/videos/redis/conf/redis.conf:/etc/redis/redis.conf
      - /home/hjh/videos/redis/logs:/logs
    command: [ "redis-server","/etc/redis/redis.conf" ]
    environment:
      - TZ="Asia/Shanghai"


  admins:
    build:
      context: ./images/admin
      dockerfile: Dockerfile
    ports:
      - "8980:8980"
    depends_on:
      - mysql
      - nacos
      - redis

#  admins01:
#    build:
#      context: ./images/admins
#      dockerfile: Dockerfile
#    ports:
#      - "8988:8980"
#    depends_on:
#      - mysql
#      - nacos
#      - redis

  category:
    build:
      context: ./images/category
      dockerfile: Dockerfile
    ports:
      - "8981:8981"
    depends_on:
      - mysql
      - nacos
      - redis

  gateway:
    build:
      context: ./images/gateway
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - mysql
      - nacos
      - redis

  users:
    build:
      context: ./images/users
      dockerfile: Dockerfile
    ports:
      - "8982:8982"
    depends_on:
      - mysql
      - nacos
      - redis

  videos:
    build:
      context: ./images/videos
      dockerfile: Dockerfile
    ports:
      - "8983:8983"
    depends_on:
      - mysql
      - nacos
      - redis

  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./admin-dist:/usr/share/nginx/html:ro
