server:
  port: 9993

spring:
  application:
    name: API-VIDEOS
  cloud:
    nacos:
      server-addr: 114.116.65.212:8848

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gz-cynosdbmysql-grp-c2m0jzh1.sql.tencentcdb.com:25224/videos?characterEncoding=UTF-8&useSSL=false
    username: root
    password: Qwer1793!
  redis:
    host: 114.116.65.212
    port: 6379
  rabbitmq:
    host: 124.222.90.112
    port: 5672
    username: guest
    password: guest
    virtual-host: / #类似于数据库概念

ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 2000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 2000


mybatis:
  mapper-locations: classpath:com/hjh/mapper/*.xml
  type-aliases-package: com.hjh.entity

logging:
  level:
    com:
      hjh:
        dao: debug
