version: "3.9"
networks:
  es_network:
services:
  es:
    image: elasticsearch:6.8.0
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
    - ./ik/:/usr/share/elasticsearch/plugins/ik
    - ./jvm.options:/usr/share/elasticsearch/config/jvm.options
    networks:
    - es_network

  kibana:
    image: kibana:6.8.0
    ports:
    - 5601:5601
    networks:
    - es_network
    volumes:
    - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
    - es